#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Compile task/scene/feature-plan inputs into Polaris Validation IR."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from polaris_env import load_env_payload, resolve_env_path


SCRIPT_DIR = Path(__file__).resolve().parent
BDD_ROOT = SCRIPT_DIR.parents[0]
WORKSPACE_ROOT = SCRIPT_DIR.parents[2]
if str(BDD_ROOT) not in sys.path:
    sys.path.insert(0, str(BDD_ROOT))

from runtime.validation_ir import build_feature_plan_ir_bundle, build_scene_validation_ir_bundle, build_validation_ir  # noqa: E402


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8-sig"))


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def resolve_workspace_path(value: str) -> Path:
    path = Path(value)
    return path if path.is_absolute() else (WORKSPACE_ROOT / path).resolve()


def main() -> int:
    parser = argparse.ArgumentParser(description="Compile Polaris Validation IR from task, scene, or compiled feature plan.")
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--task", default="")
    source.add_argument("--scene", default="")
    source.add_argument("--feature-plan", default="", help="compiled_plan.json generated by compile_feature.py")
    parser.add_argument("--env-file", default="polaris.local.json")
    parser.add_argument("--mode", default="")
    parser.add_argument("--tag", default="")
    parser.add_argument("--allow-side-effects", action="store_true")
    parser.add_argument("--out", default="")
    args = parser.parse_args()

    env_path = resolve_env_path(args.env_file, WORKSPACE_ROOT)
    env_payload = load_env_payload(env_path)
    payload: dict[str, Any]
    result = "PASS"
    default_name = "validation_ir"
    if args.task:
        task_path = resolve_workspace_path(args.task)
        ir = build_validation_ir(
            task=load_json(task_path),
            env_payload=env_payload,
            task_path=str(task_path),
            env_file=str(env_path),
            mode=args.mode,
            allow_side_effects=args.allow_side_effects,
            tag=args.tag,
        )
        payload = ir.to_dict()
        result = str(ir.constraints.get("result", "UNKNOWN") or "UNKNOWN")
        default_name = f"{ir.project_id}_{ir.task_id}.json"
    elif args.scene:
        scene_path = resolve_workspace_path(args.scene)

        def load_task_from_scene(value: str) -> dict[str, Any]:
            return load_json(resolve_workspace_path(value))

        payload = build_scene_validation_ir_bundle(
            scene=load_json(scene_path),
            env_payload=env_payload,
            load_task=load_task_from_scene,
            scene_path=str(scene_path),
            env_file=str(env_path),
            mode=args.mode,
            allow_side_effects=args.allow_side_effects,
        )
        item_results = [str(item.get("constraints", {}).get("result", "UNKNOWN")) for item in payload.get("items", [])]
        result = "FAIL" if any(item == "FAIL" for item in item_results) else "PASS"
        default_name = f"{payload.get('bundle_id', 'scene_ir').replace(':', '_')}.json"
    else:
        plan_path = resolve_workspace_path(args.feature_plan)
        payload = build_feature_plan_ir_bundle(
            feature_plan=load_json(plan_path),
            env_payload=env_payload,
            plan_path=str(plan_path),
            env_file=str(env_path),
            mode=args.mode,
            allow_side_effects=args.allow_side_effects,
        )
        item_results = [str(item.get("constraints", {}).get("result", "UNKNOWN")) for item in payload.get("items", [])]
        result = "FAIL" if any(item == "FAIL" for item in item_results) else "PASS"
        safe_bundle_id = str(payload.get("bundle_id", "feature_ir")).replace(":", "_").replace("\\", "_").replace("/", "_")
        default_name = f"{safe_bundle_id}.json"

    out = Path(args.out) if args.out else BDD_ROOT / "debug" / "validation_ir" / default_name
    if not out.is_absolute():
        out = (WORKSPACE_ROOT / out).resolve()
    write_json(out, payload)
    print(out)
    if payload.get("schema") == "polaris.validation_ir_bundle.v1":
        print(f"bundle_id={payload.get('bundle_id')} items={len(payload.get('items', []))} constraints={result}")
    else:
        print(f"ir_id={payload.get('ir_id')} constraints={result}")
    return 0 if result != "FAIL" else 1


if __name__ == "__main__":
    raise SystemExit(main())
